--- #YAML:1.0
name:               JavaScript
version:            1.12
abstract:           Perl extension for executing embedded JavaScript
author:
    - Claes Jakobsson <claesjac@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Exception:  0
    Test::More:       0
resources:
    repository:  svn://svn.versed.se/public/Perl/modules/JavaScript
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
